export enum STORE_NAMES {
  DOME = 'STORE_DEMO',
  AUTH = 'STORE_AUTH',
  APP = 'STORE_APP',
  ROUTE = 'STORE_ROUTE',
}

export enum STORAGE_NAMES {
  TOKEN = 'TOKEN',
  USER_INFO = 'USER_INFO',
}

export enum ROUTE_NAMES {
  HOME = 'HOME',
  LOGIN = 'LOGIN',
  INSPECTION = 'INSPECTION',
  SCENE = 'SCENE',
}
